---
name: light
price: 60
time_period:
  stone_age:
    armour_class: 2
    maxdex: 1
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -3
  bronze_age:
    armour_class: 3
    maxdex: 2
    dr_piercing: 1
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -1
  iron_age:
    armour_class: 3
    maxdex: 3
    dr_piercing: 1
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -2
  steel_age:
    armour_class: 4
    maxdex: 2
    dr_piercing: 1
    dr_slashing: 1
    dr_bashing: 0
    skillpenalty: -1
---
name: heavy
price: 240
time_period:
  stone_age:
    armour_class: 4
    maxdex: 0
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 1
    skillpenalty: 0
  bronze_age:
    armour_class: 5
    maxdex: 1
    dr_piercing: 0
    dr_slashing: 1
    dr_bashing: 0
    skillpenalty: -4
  iron_age:
    armour_class: 6
    maxdex: 1
    dr_piercing: 0
    dr_slashing: 1
    dr_bashing: 1
    skillpenalty: -3
  steel_age:
    armour_class: 7
    maxdex: 2
    dr_piercing: 1
    dr_slashing: 1
    dr_bashing: 1
    skillpenalty: -3
---
name: helmet
price: 12
time_period:
  stone_age:
    armour_class: 0
    maxdex: 0
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: 0
  bronze_age:
    armour_class: 1
    maxdex: -1
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -2
  iron_age:
    armour_class: 1
    maxdex: 0
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -1
  steel_age:
    armour_class: 1
    maxdex: 0
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -1
---
name: shield
price: 20
time_period:
  stone_age:
    armour_class: 1
    maxdex: -2
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -2
  bronze_age:
    armour_class: 2
    maxdex: -1
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -2
  iron_age:
    armour_class: 2
    maxdex: -1
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: -1
  steel_age:
    armour_class: 1
    maxdex: 0
    dr_piercing: 0
    dr_slashing: 0
    dr_bashing: 0
    skillpenalty: 0
---
